### ISSUE TITLE
All filters creating a red image

### ISSUE THREAD

**Issue by chrysb** [BradLarson/GPUImage2#35] opened 2016-06-18 10:04 UTC
I'm running XCode 7.3.1. I've triple checked I've followed the set up instructions.

Any filter I run, via any method (filterWithOperation, filterWithPipeline, or using PictureOutput()) the outputImage is always just a red fill.

Maybe I'm doing something wrong, but maybe others are running into this?

**Comment by chrysb** [comment] 2016-06-18 10:40
The plot thickens, it seems once I call `.filterWithOperation` twice on the same source image, the filter works. If I call it just once, the output is red.

**Comment by chrysb** [comment] 2016-06-20 04:53
As a sanity check, I added an imageview to your example code in SimpleImageFilter:

`        // Filtering image for saving
        let testImage = UIImage(named:"WID-small.jpg")!
        let toonFilter = SmoothToonFilter()
        let filteredImage = testImage.filterWithOperation(toonFilter)

        imageView.image = filteredImage`

And the output is a red image: http://imgur.com/CwowrcU

**Comment by BradLarson** [comment] 2016-06-20 17:25
This should be fixed now. The PictureInput was triggering an automatic reprocessing when it was attached as a target, but before it had been told to do so, leading to an ordering problem. I added a check around this in the latest commit, which seems to work on Mac, Simulator, and iOS devices.

**Closed by BradLarson** 2016-06-20 17:25 UTC

**Comment by Jitenderios** [comment] 2018-01-04 06:03
Hi Brad, filters creating a red image randomly. The issue is coming once in a while not always.
