### ISSUE TITLE
Why is it saying all this code in the framework was deprecated in IOS 8?

### ISSUE THREAD

**Issue by danicejewishboy** [BradLarson/GPUImage2#113] opened 2017-01-21 22:26 UTC
<img width="1038" alt="screen shot 2017-01-21 at 2 29 08 pm" src="https://cloud.githubusercontent.com/assets/22111530/22178201/30df5e3e-dfe5-11e6-9200-cf8e427d35fa.png">

I attached an image of all the code said to be deprecated. I opened up an example and was surprised to see all these warnings. I am just wondering if everything is kosher despite the warnings?

**Comment by JannyKul** [comment] 2017-01-22 19:17
https://github.com/BradLarson/GPUImage2/issues/107

**Comment by danicejewishboy** [comment] 2017-01-22 20:31
Thank you! Good call

**Comment by BradLarson** [comment] 2017-01-23 15:58
Yeah, haven't found a great way to suppress these, yet maintain backwards compatibility yet. For now, I'm leaving the warnings, as I stated in the other issue. I'll mark this as a duplicate of that.

**Closed by BradLarson** 2017-01-23 15:58 UTC
